#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# Initialize a counter variable
i=0

# Use until loop to print "Best School" 10 times
until ((i >= 10))
do
    echo "Best School"
    # Increment the counter
    ((i++))
done
